using System.Text.Json;
using Azure.Identity;
using Azure.Messaging.EventHubs;
using Azure.Messaging.EventHubs.Producer;
using AzRadar.Shared.Configuration;
using AzRadar.Shared.Interfaces;
using AzRadar.Shared.Models;
using Microsoft.Extensions.Options;

namespace AzRadar.Shared.Services;

public class ServiceHealthTestEventPublisher : IServiceHealthTestEventPublisher, IAsyncDisposable
{
    private readonly ServiceHealthEventHubSettings _settings;
    private readonly EventHubProducerClient? _producer;

    public ServiceHealthTestEventPublisher(IOptions<ServiceHealthEventHubSettings> options)
    {
        _settings = options.Value;
        if (!string.IsNullOrWhiteSpace(_settings.FullyQualifiedNamespace) &&
            !string.IsNullOrWhiteSpace(_settings.EventHubName) &&
            !string.IsNullOrWhiteSpace(_settings.ManagedIdentityClientId))
        {
            var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions
            {
                ManagedIdentityClientId = _settings.ManagedIdentityClientId
            });
            _producer = new EventHubProducerClient(
                _settings.FullyQualifiedNamespace,
                _settings.EventHubName,
                credential);
        }
    }

    public async Task<ServiceHealthTestEventResult> PublishAsync(
        string subscriptionId,
        string eventType,
        CancellationToken cancellationToken = default)
    {
        if (!_settings.EnableTestPublisher)
            throw new InvalidOperationException("Synthetic Service Health event publishing is disabled.");
        if (_producer == null)
            throw new InvalidOperationException("Service Health Event Hub settings are incomplete.");
        if (!ServiceHealthEventTypes.Supported.Contains(eventType))
            throw new ArgumentException($"Unsupported Service Health event type '{eventType}'.", nameof(eventType));

        var eventDataId = Guid.NewGuid().ToString();
        var trackingId = $"TEST-{DateTimeOffset.UtcNow:yyyyMMddHHmmss}";
        var incidentType = eventType switch
        {
            ServiceHealthEventTypes.ServiceIssue => "Incident",
            ServiceHealthEventTypes.PlannedMaintenance => "Maintenance",
            ServiceHealthEventTypes.SecurityAdvisory => "SecurityAdvisory",
            _ => "ActionRequired"
        };
        var operationSegment = eventType switch
        {
            ServiceHealthEventTypes.ServiceIssue => "incident",
            ServiceHealthEventTypes.PlannedMaintenance => "maintenance",
            ServiceHealthEventTypes.SecurityAdvisory => "security",
            _ => "actionrequired"
        };
        var now = DateTimeOffset.UtcNow;
        var envelope = new
        {
            records = new[]
            {
                new
                {
                    time = now,
                    eventTimestamp = now,
                    eventDataId,
                    correlationId = Guid.NewGuid().ToString(),
                    category = "ServiceHealth",
                    operationName = $"Microsoft.ServiceHealth/{operationSegment}/action",
                    resourceId = $"/subscriptions/{subscriptionId}",
                    resultType = "Active",
                    level = "Informational",
                    properties = new
                    {
                        title = $"AzRadar synthetic {eventType} test",
                        communication = "Synthetic Service Health event generated by AzRadar to validate the private Event Hub ingestion pipeline.",
                        service = "Azure Test Service",
                        region = "Central US",
                        incidentType,
                        trackingId,
                        synthetic = true
                    }
                }
            }
        };

        var eventData = new EventData(BinaryData.FromObjectAsJson(
            envelope,
            new JsonSerializerOptions(JsonSerializerDefaults.Web)))
        {
            ContentType = "application/json",
            MessageId = eventDataId,
            CorrelationId = trackingId
        };
        eventData.Properties["azRadarSynthetic"] = true;

        using var batch = await _producer.CreateBatchAsync(cancellationToken);
        if (!batch.TryAdd(eventData))
            throw new InvalidOperationException("The synthetic Service Health event exceeds the Event Hub batch size.");
        await _producer.SendAsync(batch, cancellationToken);

        return new ServiceHealthTestEventResult(eventDataId, trackingId, eventType, now);
    }

    public async ValueTask DisposeAsync()
    {
        if (_producer != null)
            await _producer.DisposeAsync();
    }
}
